var game_dict = {
	"Among the Sleep": "among_sleep.jpg",
	"Azur Lane: Crosswave": "azur_lane.jpg",
	"Baba is You": "baba_you.jpg",
	"Betty's Beer Bar": "betty_beer.jpg",
	"Genshin Impact": "genshin_impact.jpg",
	"Harvest Moon: Save the Homeland": "harvest_moon.jpg",
	"Layers of Fear": "layers_fear.jpg",
	"P.T.": "P.T.jpg",
	"Phasmaphobia": "phasmaphobia.jpg",
	"Surgeon Simulator": "surgeon_simulator.jpg",
	"Visage": "visage.jpg",
	"Amnesia: The Dark Descent": "amnesia.jpg",
	"Among Us": "among_us.png",
	"Bioshock": "bioshock.jpg",
	"Ultimate Chicken Horse": "chicken_horse.jpg",
	"Civilization V": "civ5.png",
	"Cooking Simulator": "cooking_simulator.jpg",
	"Crusader King": "crusader_king.jpg",
	"Cultist Simulator": "cultist_simulator.png",
	"Dark Deception": "dark_deception.jpg",
	"Dark Miasma": "dark_miasma.jpg",
	"Final Fantasy Dissidia": "dissidia.jpg",
	"Final Fantasy VII": "ff7.jpg",
	"Final Fantasy VIII": "ff8.png",
	"Final Fantasy X": "ff10.jpg",
	"Final Fantasy XIII": "ff13.jpg",
	"Final Fantasy XV": "ff15.jpg",
	"Final Fantasy": "final_fantasy.jpg",
	"Firewatch": "firewatch.jpg",
	"Five Nights at Freddy's": "five_nights.jpg",
	"Goat Simulator": "goat_simulator.jpg",
	"Guild Wars 2": "guild_wars2.jpg",
	"Guitar Hero": "guitar_hero.jpg",
	"Hearthstone": "hearthstone.jpg",
	"Injustice: Gods Among Us": "injustice.jpg",
	"Kingdom Come: Deliverance": "kingdom_come.jpg",
	"L.A. Noire": "la_noire.jpg",
	"Man of Medan": "man_medan.jpg",
	"Maneater": "maneater.jpg",
	"Megaman": "megaman.jpg",
	"Metal Slug": "metal_slug.jpg",
	"Moving Out": "moving_out.jpg",
	"Need for Speed": "need_speed.png",
	"Not for Broadcast": "not_for_broadcast.jpg",
	"Outer Worlds": "outer_worlds.jpg",
	"Outlast": "outlast.jpg",
	"Overcooked": "overcooked.jpg",
	"Plague Inc.": "plague_inc.jpg",
	"Plug & Play": "plug_play.png",
	"Red Dead Redemption": "red_redemption.jpg",
	"Roller Coaster Tycoon": "roller_coaster.png",
	"SpongeBob SquarePants: Battle for Bikini Bottom": "spongebob.jpg",
	"The SpongeBob SquarePants Movie": "spongebob_movie.jpg",
	"The Escapists": "the_escapists.jpg",
	"Thief Simulator": "thief_simulator.png",
	"Uno: Shadow Game": "uno.jpg",
	"Yakuza": "yakuza.jpg",
	"Yandere Simulator": "yandere_simulator.jpg",
	"Youtubers Life": "youtubers_life.jpg",
	"Zoo Tycoon": "zoo_tycoon.jpg",
	"Age of Empires 2": "age_empires.jpg",
	"Anthem": "anthem.jpg",
	"Apex Legends": "apex_legends.jpg",
	"Batman: Arkham Asylum": "arkham_asylum.jpg",
	"Batman: Arkham City": "arkham_city.jpg",
	"Batman: Arkham Knight": "arkham_knight.jpg",
	"Call of Duty: Black Ops": "black_ops.jpg",
	"Bloodborne": "bloodborne.jpg",
	"Call of Cthulhu": "call_cthulhu.jpg",
	"Call of Duty: Modern Warfare 2": "cod_mw2.jpg",
	"Sherlock Holmes: Crimes & Punishments": "crimes_punishment.jpg",
	"Cuphead": "cuphead.jpg",
	"Dark Souls 3": "dark_souls_3.jpg",
	"Dead By Daylight": "dead_by_daylight.jpg",
	"Destiny 2": "destiny2.png",
	"Diner Dash": "diner_dash.png",
	"Fall Guys": "fall_guys.jpg",
	"Fortnite": "fortnite.jpg",
	"Grand Theft Auto 5": "gta_5.jpg",
	"Grand Theft Auto: San Andreas": "gta_andreas.png",
	"Hitman": "hitman.jpg",
	"Horizon Zero Dawn": "horizon_zero.jpg",
	"The Jackbox Party Pack": "jackbox.jpg",
	"Watch Dogs: Legion": "legion.jpg",
	"Life Is Strange": "life_strange.jpg",
	"Payday 2": "payday2.jpg",
	"PlayerUnknown's Battlegrounds": "pubg.jpg",
	"Resident Evil 2": "resident_evil2.jpg",
	"Resident Evil 4": "resident_evil4.jpg",
	"Resident Evil 5": "resident_evil5.jpg",
	"Resident Evil 7": "resident_evil7.jpg",
	"Sea of Thieves": "sea_thieves.jpg",
	"The Sinking City": "sinking_city.jpg",
	"Stardew Valley": "stardew_valley.jpg",
	"Terraria": "terraria.jpg",
	"Tetris": "tetris.jpg",
	"Until Dawn": "until_dawn.jpg",
	"Valorant": "valorant.jpg",
	"Watch Dogs": "watch_dogs.jpg",
	"World of Warships": "world_warships.jpg",
	"World of Warcraft": "wow.jpg",
	"Yomawari: Midnight Shadow": "yomawari.jpg",
	"Morrowind": "morrowind.jpg",
	"Arknights": "arknights.jpg",
	"Assassin's Creed": "assassins_creed.jpg",
	"Assassin's Creed 2": "assassins_creed2.jpg",
	"Assassin's Creed 3": "assassins_creed3.jpg",
	"Bioshock: Infinite": "bioshock_infinite.jpg",
	"Assassin's Creed: Black Flag": "black_flag.jpg",
	"Borderlands 3": "borderlands_3.jpg",
	"Catherine": "catherine.jpg",
	"Cooking Mama": "cooking_mama.jpg",
	"Death Stranding": "death_stranding.jpg",
	"Fallout 3": "fallout3.jpg",
	"Fallout 4": "fallout4.jpg",
	"Fire Emblem: Three Houses": "fire_emblem_houses.jpg",
	"For Honor": "for_honor.jpg",
	"Just Cause 3": "just_cause.jpg",
	"Kingdom Hearts": "kingdom_hearts.jpg",
	"Kingdom Hearts 2": "kingdom_hearts2.jpeg",
	"Kingdom Hearts 3": "kingdom_hearts3.jpg",
	"Left 4 Dead": "left_4_dead.png",
	"Little Nightmares": "little_nightmares.jpg",
	"Luigi Mansion 3": "luigi_mansion.jpg",
	"Mario Kart": "mario_kart.jpg",
	"Metal Gear Solid": "metal_gear.jpg",
	"Metal Gear Solid 3": "metal_gear3.jpg",
	"Metal Gear Solid 4": "metal_gear4.jpg",
	"Oblivion": "oblivion.jpg",
	"Assassin's Creed: Odyssey": "odyssey.jpg",
	"Order 1886": "order_1886.jpg",
	"Assassin's Creed: Origins": "origins.jpg",
	"Overwatch": "overwatch.jpg",
	"Persona 3": "persona3.jpg",
	"Persona 4": "persona4.jpg",
	"Persona 5": "persona5.png",
	"Hatsune Miku: Project Diva": "project_diva.jpg",
	"Sword Art Online": "sao.jpg",
	"Skyrim": "skyrim.png",
	"Sonic the Hedgehog": "sonic.jpg",
	"Splinter Cell": "splinter_cell.jpg",
	"Stanley Parable": "stanley_parable.jpg",
	"Super Mario Bros": "super_mario.jpg",
	"The Sims": "the_sims.jpg",
	"Thief": "thief.jpg",
	"Tomb Raider": "tomb_raider.jpg",
	"Uncharted 2": "uncharted2.jpg",
	"Uncharted 4": "uncharted4.jpg",
	"Undertale": "undertale.png",
	"Assassin's Creed: Unity": "unity.jpg",
	"Vampyr": "vampyr.jpg",
	"The Witcher 2": "witcher2.jpg",
	"The Witcher 3": "witcher3.jpg"
}